# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


MANDRILL_USERNAME: copilot.travel@gmail.com
MANDRILL_API_KEY: t4qWX9vP9PA5-P6FglhRyQ
MAILCHIMP_API_KEY: 206b62034de52c05c2b78b9cc61240e8-us8
MAILCHIMP_LIST_ID: 6efaa8c0e0
ADMIN_NAME: Admin
ADMIN_EMAIL: copilot.travel@gmail.com
ADMIN_PASSWORD: password
ROLES: [admin, user]
EMAIL_ADDRESS: hello@copilot.travel
DOMAIN: www.copilot.travel
